<?php

namespace Configuration;
require '../../vendor/autoload.php';
use Configuration\Parser\PHPParser;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-09 at 16:57:13.
 */
class ConfigurationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Configuration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Configuration;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Configuration\Configuration::attachParser
     */
    public function testAttachParser() {
        $this->object->attachParser(new PHPParser);
        $this->assertCount(2,$this->object->count());
    }

    /**
     * @covers Configuration\Configuration::dettachParser
     */
    public function testDettachParser() {
         $this->object->dettachParser(new PHPParser);
        $this->assertCount(1,$this->object->count());
    }

    /**
     * @covers Configuration\Configuration::count
     */
    public function testCount() {       
        $this->object->attachParser(new PHPParser);
        $this->assertCount(2,$this->object->count());
    }

    /**
     * @covers Configuration\Configuration::factory
     */
    public function testFactory() {
         $this->object->attachParser(new PHPParser);
        $this->assertEquals(PHPParser::class,get_class($this->object->factory('../config.php')));
    }

}
